# site settings
title: four.sg
subtitle: by stardust2810
email: stardust2810@gmail.com
description: A personal blog on the ups and downs of the Ng Family.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: stardust2810
street_address: null
city: null
state: null
zip_code: null
country: tiny island somewhere in the pacific
phone: null

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 20

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/stardust2810
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/stardust2810
  Twitter: https://twitter.com/stardust2810
  Facebook:
  Slack:

# build settings
markdown: kramdown
theme: "forty-jekyll-theme"

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
